#!/usr/bin/python3

import urllib.parse as ul
import os
import sys
import select
import signal
import argparse
import re
import subprocess
from subprocess import check_output, PIPE, Popen, TimeoutExpired

#EXECPATH = os.path.dirname(os.path.abspath(__file__))
EXECPATH = os.path.abspath('/videos')
os.chdir(EXECPATH)
RUNNING_PROCS = set()
SHUTDOWN = False                                               

class VideoEdit(object):

    @staticmethod
    def dl(cmdline_args):
        if cmdline_args.url is not None:
            url = ul.urlparse(f"{cmdline_args.url}").geturl()
        else:
            exit(2)
        dl_command = ['youtube-dl', '--prefer-ffmpeg', '-f', 'bestvideo+bestaudio', '--fixup', 'detect_or_warn', '--no-cache-dir', '--no-playlist', '--print-traffic', '--no-call-home']
        user_agent = re.escape(cmdline_args.user_agent)
        output_file = ""
        if cmdline_args.format is not None:
            dl_command.extend(['--recode-video', cmdline_args.format])
        if cmdline_args.out_file_name is not None:
            output_file = cmdline_args.out_file_name
        else:
            id_command = ['youtube-dl', '--no-cache-dir', '--get-id', '--no-call-home', url]
            output_file = VideoEdit.__run_command(id_command)
        dl_command.extend(['-o', output_file, '--user-agent', user_agent, url])
        VideoEdit.__run_command(dl_command)
        print(f'\n~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~\nvideo saved as {output_file}\n~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~')

    @staticmethod
    def edit(cmdline_args):
        in_file = os.path.abspath(f'{EXECPATH}/{cmdline_args.in_file_name}')
        out_file = cmdline_args.out_file_name
        start_time = re.escape(cmdline_args.start_time)
        end_time = re.escape(cmdline_args.end_time)
        command = ['ffmpeg', '-i', in_file, '-ss', start_time, '-to', end_time, '-c', 'copy', out_file]
        VideoEdit.__run_command(command)

    @staticmethod
    def __run_command(command, timeout=0):
        res = None
        if command != '':
            print('executing: ', ' '.join(command))
            process = Popen(command, stdout=PIPE, universal_newlines=True)
            RUNNING_PROCS.add(process)
            try:
                res = process.communicate()[0].strip()
                print(f'Result: {res}')
            except TimeoutExpired:
                process.kill()
                _, err = process.communicate()
                exit(err)
            finally:
                RUNNING_PROCS.remove(process)
        return res

    @staticmethod
    def __mkdir(path):
        if not os.path.isdir(path) or not os.path.exists(path):
            os.mkdir(path)
        return path


def handle_signal(signum, frame):
    # send signal recieved to subprocesses
    global SHUTDOWN
    SHUTDOWN = True
    for proc in RUNNING_PROCS:
        if proc.poll() is None:
            proc.send_signal(signum)

signal.signal(signal.SIGINT, handle_signal)
signal.signal(signal.SIGTERM, handle_signal)

arg_parser = argparse.ArgumentParser(
    description='Download and locally edit hosted video content.')

arg_parser.add_argument('--url',
                        type=str,
                        help='remote video url')
arg_parser.add_argument('--format',
                        choices=['mp4', 'flv', 'ogg', 'webm', 'mkv', 'avi'],
                        help='output video format')
arg_parser.add_argument('--user_agent',
                        type=str,
                        default='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.74 Safari/537.36 Edg/79.0.309.43',
                        help='downloader user-agent')
arg_parser.add_argument('--start_time',
                        type=str,
                        help='video clip start time')
arg_parser.add_argument('--end_time',
                        type=str,
                        help='video clip end time')
arg_parser.add_argument('--in_file_name',
                        type=str,
                        help='editor input video file name path')
arg_parser.add_argument('--out_file_name',
                        type=str,
                        help='editor output video file')
arg_parser.add_argument('operation',
                        choices=['dl', 'edit'],
                        help='video editor and downloader commands')

if __name__ == '__main__':
    cmdline_args = arg_parser.parse_args()
    cmd = cmdline_args.operation
    if cmd == 'dl':
        VideoEdit.dl(cmdline_args)
    if cmd == 'edit':
        VideoEdit.edit(cmdline_args)
